language: cpp

os: linux

dist: trusty
sudo: enabled

services:
  - docker

notifications:
    email:
      on_success: never  # default: change
      on_failure: always # default: always

before_script:
  - docker build -t ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_NUMBER} . -f Test.Dockerfile

script:
  # It runs the tests into the Docker container.
  - docker run ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} /bin/bash -c "cd /tmp/producer_consumer; ./scripts/run-all-tests.sh"

after_success:
  - docker run -it --workdir /opt/shared --name=docker-environment --rm -v `pwd`:/opt/shared
      ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} /bin/bash
      -c "scripts/build-application.sh; scripts/run-all-tests.sh; scripts/run-gcov-coverage-report.sh"
  - bash <(curl -s https://codecov.io/bash)
