#ifndef Foundation_Util_Path_INCLUDED
#define Foundation_Util_Path_INCLUDED

#include <string>
#include "Foundation/Foundation.h"

namespace Foundation {
namespace Util {


    /**
     * This structure makes available application Paths.
     * The path values are injected in build time in the CMakeAutogenerated file.
     */
    struct API Path
    {
        const static std::string APPLICATION_HOME_DIRECTORY_PATH;
            /// Application directory installation (default.: /usr/local).

        const static std::string APPLICATION_BINARY_DIRECTORY_PATH;
            /// Application directory installation (default.: /usr/local/bin).

        static std::string addSeparatorTo(const std::string & path);

    };


} }

#endif
