#-----------------------------------------------------------------------------
# Those constants are used in the application code through the Foundation/Util/Path class.
#
# See.:
#   - data/source/CMakeAutogenerated.h.in
#   - Foundation/Util/CMakeAutogenerated.h
#
#-----------------------------------------------------------------------------
set(APPLICATION_HOME_DIRECTORY ${CMAKE_HOME_DIRECTORY})

configure_file(
    "${CMAKE_HOME_DIRECTORY}/data/source/CMakeAutogenerated.h.in"
    "${CMAKE_HOME_DIRECTORY}/build/source/Foundation/Util/CMakeAutogenerated.h"
)

configure_file(
    "${CMAKE_HOME_DIRECTORY}/build/source/Foundation/Util/CMakeAutogenerated.h"
    "${CMAKE_HOME_DIRECTORY}/Foundation/include/Foundation/Util/CMakeAutogenerated.h"
    COPYONLY
)
